[project]
name = "toeic4all-admin"
version = "0.1.0"
description = "Toeic Question Generation by LLM"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.15.0",
    "pymongo>=4.13.0",
    "python-dotenv>=1.1.0",
]

[dependency-groups]
dev = []
