# Default values for retriever.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: toeic4all

replicaCount: 1

image:
  repository: 192.168.0.5:5000/toeic4all-admin
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: LoadBalancer
  port: 80

jwtSecretKey: ""
